/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import Head from 'next/head'
import React from 'react';
import { styled } from '@mui/material/styles';



const Desktop11 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `2004px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Desktop12 = styled('div')({
  backgroundColor: `rgba(232, 222, 209, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `3080px`,
  height: `2004px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const WelcomeToMyPortfolio = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(21, 63, 213, 1)`,
  fontStyle: `italic`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `96px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `438px`,
  top: `95px`,
});

const Profilepicture1 = styled('img')({
  height: `393px`,
  width: `589px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `2346px`,
  top: `82px`,
});

const CybersecurityAndCodi = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `italic`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `48px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `571px`,
  top: `278px`,
});

const AboutMeSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `64px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const AboutMeSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `italic`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `64px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const AboutMe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `64px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `2530px`,
  top: `575px`,
});

const MyBiography = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.5)`,
  fontStyle: `italic`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `48px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `846px`,
  top: `546px`,
});

const MyNameIsSandraGeorge = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `48px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `235px`,
  top: `654px`,
});
const Mailchimp = styled('div')({
  textAlign: `center`,
  position: `absolute`,
  left: `200px`,
  top: `1000px`,
  right: `1000px`,
});

const YouCanContactMeUsing = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `italic`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `580px`,
  top: `1925px`,
});

const LinkedinIn1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `37px`,
  height: `48.03px`,
  left: `1130px`,
  top: `1906px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `42.03px`,
  width: `37px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Github1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `45px`,
  height: `39px`,
  left: `1251px`,
  top: `1913px`,
  overflow: `hidden`,
});

const Vector1 = styled('img')({
  height: `36.84px`,
  width: `45px`,
  position: `absolute`,
  left: `0px`,
  top: `1px`,
});

const Vector2 = styled('img')({
  height: `33.72px`,
  width: `59px`,
  position: `absolute`,
  left: `1398px`,
  top: `1916px`,
});


function Desktop1(props) {
  return (
           <Desktop11 className={props.className}>
             <Head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-PGC6GPXTT2"></script>
        <script>
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag() {
            window.dataLayer.push(arguments);
          }
          gtag('js', new Date());
          gtag('config', 'G-PGC6GPXTT2');
          `}
        </script>
      </Head>
  
      <Desktop12>
        <WelcomeToMyPortfolio>
          {`Welcome to my portfolio!`}
        </WelcomeToMyPortfolio>
        <Profilepicture1
          src={`assets/images/Desktop1_profilepicture_1.png`}
          loading="lazy"
          alt={'profilepicture 1'}
        />
        <CybersecurityAndCodi>
          {`Cybersecurity and coding enthusiast`}
        </CybersecurityAndCodi>
        <AboutMe>
        <a href='https://www.figma.com/proto/4VozhPunxEXe4xetDcUKdJ/Untitled?type=design&node-id=1-4&t=5gTkJirRhYgJjNwD-1&scaling=min-zoom&page-id=0%3A1&mode=design'>About me</a>
        </AboutMe>
        <MyBiography>{`My biography`}</MyBiography>
        <MyNameIsSandraGeorge>
          {`My name is Sandra George, I am 29 years old. I am originally from Egypt. I came to
the States in 2011. I live in New Jersey. I graduated Rutgers with a degree in 
Information Technology with most courses focusing on Cybersecurity, as I want to
 have a career in cybersecurity. I am currently employed with TCS and looking for 
a better job in my field. I love music, sports, psychology and technology`}

        </MyNameIsSandraGeorge>
        <Mailchimp>
        <iframe src="/test.html" width="100%" height="250"></iframe>
        </Mailchimp>
       
        <YouCanContactMeUsing>
          {`You can contact me using these links :`}
        </YouCanContactMeUsing>
        <LinkedinIn1>
          <Vector
            src={`assets/images/Desktop1_Vector.png`}
            loading="lazy"
            alt={'Vector'}
          />
        </LinkedinIn1>
        <Github1>
          <Vector1
            src={`assets/images/Desktop1_Vector_1.png`}
            loading="lazy"
            alt={'Vector'}
          />
        </Github1>
        <Vector2
          src={`assets/images/Desktop1_Vector_2.png`}
          loading="lazy"
          alt={'Vector'}
        />
      </Desktop12>
    </Desktop11>
  );
}

export default Desktop1;
